# -*- coding: utf-8 -*-
"""Penrith belt, the unit-and-strata suburbs, and the Hawkesbury."""
from sub_data_a import FEE, LIC, AH, council_q

STRATA = ("It depends where the blockage actually is. Inside your own fixtures and branch lines it is "
          "normally yours. In the shared stack or common drainage it is normally the building's. We "
          "find out which before anybody commits to paying, and we can put that in writing for your "
          "strata manager.")

SUBS = [

{
 'slug': 'plumber-mount-druitt', 'name': 'Mount Druitt', 'pc': '2770',
 'title': 'Plumber Mount Druitt | 24/7 Emergency | Straight Away Plumbing',
 'og': 'Plumber Mount Druitt | 24/7 Emergency Plumbing',
 'desc': 'Licensed plumber servicing Mount Druitt 2770. Blocked drains, tree roots, old pipework, hot water. 24/7, $0 call out fee. Call 0403 322 290.',
 'ld_desc': 'Licensed plumber servicing Mount Druitt NSW 2770. Tree root removal, blocked drains, corroded pipework, hot water systems and 24/7 emergency callouts, with no call out fee.',
 'hero': 'Licensed plumbing across Mount Druitt - 24 hours a day, with no call out fee and free quotes. Call and we will tell you straight away when we can be there.',
 'h2': 'Built Fast, and Built All At Once',
 'paras': [
   'Mount Druitt went up quickly through the 1960s and 70s, and a great deal of it was built to the same specification at the same time. Sixty years on, that shows in the plumbing.',
   'Same materials, same age, same failures, arriving in roughly the same order: earthenware sewer under mature trees, galvanised water pipe at the end of its life, and hot water systems that were replaced once and are now overdue again.',
   'The advantage of a suburb like this is that very little about it is a mystery. We have almost certainly been inside the same house before.',
 ],
 'cards_intro': 'Housing built to one pattern, wearing out to the same pattern sixty years later.',
 'cards': [
   ('jet', 'Tree roots in earthenware sewer', 'Sixty-year-old drainage under trees the same age. Roots get in at the joints and catch everything. Jetted out, then a camera to check whether the pipe is still sound.'),
   ('pipe', 'Galvanised pipe at the end of its life', 'Low pressure and discoloured water. The bore narrows from the inside until almost nothing gets through. Replaced in sections or in full, whichever actually makes sense.'),
   ('hot', 'Hot water due again', 'A unit replaced twenty years ago is now as old as the one it replaced. We will give you a straight answer on whether a repair is worth doing.'),
   ('drain', 'Blocked kitchen and laundry waste', 'Decades of fat, grit and detergent narrowing a waste line until it stops. A jetter restores it properly; a supermarket drain cleaner does not.'),
   ('tap', 'Taps and toilets', 'Old tapware and cistern parts that have been dripping or running for years. Quick to repair, and it shows up on the next bill.'),
   ('alert', 'Emergency callouts', 'Burst pipes, gas leaks and sewer overflows, 24 hours a day. Pipework this age does not choose a convenient moment.'),
 ],
 'nearby_eyebrow': 'Around Western Sydney',
 'nearby_intro': 'We are through this part of Western Sydney most days. If your suburb is not listed here, search the full list or just call and ask.',
 'nearby': ['plumber-rooty-hill', 'plumber-doonside', 'plumber-blacktown', 'plumber-st-marys', 'plumber-penrith', 'plumber-marsden-park'],
 'faqs': [
   ('Do you charge a call out fee in Mount Druitt?', FEE),
   ('The same drain blocks every year. Can that be stopped?', 'Usually, yes - but not by clearing it again. If it comes back on a schedule there is a crack or an open joint letting roots in, and that section needs relining or replacing to actually end it. A camera inspection shows you the break so you are deciding on evidence rather than guessing.'),
   ('Is it worth repiping the whole house or just the bad section?', 'Depends how much of it is galvanised and how bad it is. If one branch is restricted, replacing that run solves it. If the whole house is original and the pressure is poor everywhere, doing it piecemeal usually costs more in the end. We will tell you which situation you are in rather than quoting the bigger job automatically.'),
   ('Do you come out to Mount Druitt after hours?', AH),
   council_q('Mount Druitt', 'Blacktown City Council'),
   ('Are you licensed and insured?', LIC),
 ],
},

{
 'slug': 'plumber-st-marys', 'name': 'St Marys', 'pc': '2760',
 'title': 'Plumber St Marys | 24/7 Emergency | Straight Away Plumbing',
 'og': 'Plumber St Marys | 24/7 Emergency Plumbing',
 'desc': 'Licensed plumber servicing St Marys 2760. Homes and shopfronts - blocked drains, old pipework, hot water. 24/7, $0 call out fee. Call 0403 322 290.',
 'ld_desc': 'Licensed plumber servicing St Marys NSW 2760, residential and commercial. Tree root removal, blocked drains, CCTV inspections, corroded pipework, hot water systems and 24/7 emergency callouts.',
 'hero': 'Licensed plumbing across St Marys - homes and businesses, 24 hours a day, with no call out fee and free quotes.',
 'h2': 'An Old Centre With Older Plumbing',
 'paras': [
   'St Marys has been a town in its own right far longer than most of the suburbs around it, and the housing reflects that - a lot of postwar building, and a fair amount that predates it.',
   'The older the house, the more likely the drainage is earthenware and the water pipe is galvanised, and the more likely nobody has looked properly at either in decades.',
   'There is also a good deal of shopfront and commercial work through the centre, which brings its own requirements: compliance, grease management, and getting the job done without closing the business for a day.',
 ],
 'cards_intro': 'Old housing and an old town centre, with commercial work alongside the residential.',
 'cards': [
   ('jet', 'Tree roots in old drainage', 'Earthenware lines with decades of tree growth over them. Roots find the joints and catch everything that passes. Cleared with a jetter, then inspected.'),
   ('pipe', 'Corroded water pipe', 'Falling pressure and rusty water in a house that has never been repiped. Replaceable section by section or in full.'),
   ('cctv', 'CCTV drain inspections', 'On an old property nobody knows what the drainage is made of or where it runs. A camera answers both without digging a hole to find out.'),
   ('hot', 'Hot water systems', 'Repairs and replacements, including the awkward installs that come with older houses.'),
   ('wrench', 'Shops and commercial premises', 'Blockages, grease management, tapware and compliance work for businesses through the centre - scheduled around trading where we can.'),
   ('storm', 'Stormwater and gutters', 'Mature trees packing the stormwater line until it backs up and sends the water down the wall instead of to the street.'),
 ],
 'nearby_eyebrow': 'Around Penrith',
 'nearby_intro': 'We are out this way most days. If your suburb is not listed here, search the full list or just call and ask.',
 'nearby': ['plumber-penrith', 'plumber-mount-druitt', 'plumber-glenmore-park', 'plumber-rooty-hill', 'plumber-doonside', 'plumber-blacktown'],
 'faqs': [
   ('Do you charge a call out fee in St Marys?', FEE),
   ('Do you do work for businesses, not just houses?', 'Yes. Shops, offices, cafes and commercial premises, one-off repairs through to ongoing maintenance. Where the work would disrupt trading we will schedule around it, including outside hours at no extra call out charge.'),
   ('My house is quite old. Is the drainage likely to be original?', 'On a lot of St Marys housing, yes - and if it is earthenware it will have joints that roots can get into. That is not a reason to panic, but it is a good reason to have a camera put down it before you spend money on landscaping or a renovation over the top.'),
   ('Do you come out to St Marys after hours?', AH),
   council_q('St Marys', 'Penrith City Council'),
   ('Are you licensed and insured?', LIC),
 ],
},

{
 'slug': 'plumber-penrith', 'name': 'Penrith', 'pc': '2750',
 'title': 'Plumber Penrith | 24/7 Emergency | Straight Away Plumbing',
 'og': 'Plumber Penrith | 24/7 Emergency Plumbing',
 'desc': 'Licensed plumber servicing Penrith 2750. Homes, units and businesses - blocked drains, hot water, leaks. 24/7, $0 call out fee. Call 0403 322 290.',
 'ld_desc': 'Licensed plumber servicing Penrith NSW 2750, residential, strata and commercial. Blocked drains, tree roots, hot water systems, shared stacks and 24/7 emergency callouts, with no call out fee.',
 'hero': 'Licensed plumbing across Penrith - homes, units and businesses, 24 hours a day, with no call out fee and free quotes.',
 'h2': 'A Centre, a Mix of Eras, and a Lot of Units',
 'paras': [
   'Penrith spans more housing types than most suburbs: older homes near the centre, postwar streets around them, newer estates on the edges, and a growing amount of unit development close in.',
   'Which means there is no single Penrith plumbing problem. An old weatherboard near the centre and a two-bedroom unit off the high street need completely different work, and there is commercial premises in between.',
   'The common thread is that the older the building, the more likely the answer is in the pipework rather than in the fixture everybody is looking at.',
 ],
 'cards_intro': 'A regional centre with every kind of building in it, and a different job in each.',
 'cards': [
   ('block', 'Units and shared stacks', 'A blockage in a shared stack shows up at the lowest fixture on the line, which is rarely the one causing it. We establish where it actually is, and whose it is, before anybody pays.'),
   ('wrench', 'Shops, offices and commercial', 'Blockages, tapware, hot water and compliance work for businesses. Scheduled around trading where we can, at no extra call out charge after hours.'),
   ('jet', 'Tree roots in the older streets', 'Established gardens over earthenware drainage. Roots get into the joints and catch everything. Jetted clear, with a camera afterwards to check the pipe.'),
   ('pipe', 'Old water pipe', 'Low pressure and discoloured water on anything that has never been repiped. Replaced in sections or in full, whichever is genuinely worth doing.'),
   ('hot', 'Hot water systems', 'Repairs and replacements across houses, units and commercial premises, including systems in awkward locations.'),
   ('alert', '24/7 emergency callouts', 'Burst pipes, gas leaks, sewer overflows and dead hot water, any hour, with no call out fee.'),
 ],
 'nearby_eyebrow': 'Around Penrith',
 'nearby_intro': 'We are out this way most days. If your suburb is not listed here, search the full list or just call and ask.',
 'nearby': ['plumber-st-marys', 'plumber-glenmore-park', 'plumber-mount-druitt', 'plumber-rooty-hill', 'plumber-richmond', 'plumber-windsor'],
 'faqs': [
   ('Do you charge a call out fee in Penrith?', FEE),
   ('I am in a unit. Is a blocked drain my problem or the building\'s?', STRATA),
   ('Do you work on commercial premises?', 'Yes. Shops, offices, cafes and commercial sites, one-off repairs through to ongoing maintenance. Where work would disrupt trading we will schedule around it, and there is no after hours call out charge for doing so.'),
   ('Do you come out to Penrith after hours?', AH),
   council_q('Penrith', 'Penrith City Council'),
   ('Are you licensed and insured?', LIC),
 ],
},

{
 'slug': 'plumber-glenmore-park', 'name': 'Glenmore Park', 'pc': '2745',
 'title': 'Plumber Glenmore Park | 24/7 | Straight Away Plumbing',
 'og': 'Plumber Glenmore Park | 24/7 Emergency Plumbing',
 'desc': 'Licensed plumber servicing Glenmore Park 2745. Hot water, slab leaks, blocked drains, renovations. 24/7, $0 call out fee. Call 0403 322 290.',
 'ld_desc': 'Licensed plumber servicing Glenmore Park NSW 2745. Hot water replacement, slab leak location, blocked drains and tree roots, renovations and 24/7 emergency callouts, with no call out fee.',
 'hero': 'Licensed plumbing across Glenmore Park - 24 hours a day, with no call out fee and free quotes. Call and we will tell you straight away when we can be there.',
 'h2': 'A Nineties Estate, Thirty Years On',
 'paras': [
   'Glenmore Park was built as a single estate through the 1990s, so the housing is broadly the same age and broadly the same specification.',
   'Thirty years is exactly the point where the original hot water has already been replaced once, the tapware is on its last legs, and bathrooms are being redone right across the suburb at the same time.',
   'It is also the era where houses went onto concrete slabs as standard, which changes what a leak looks like and how you find it.',
 ],
 'cards_intro': 'An estate built in one decade, now hitting its second round of replacements together.',
 'cards': [
   ('hot', 'Hot water, second time around', 'The unit that replaced the original is now about the age the original was when it failed. We will tell you honestly how much life is left rather than pushing a sale.'),
   ('pipe', 'Leaks under the slab', 'On slab-on-ground housing a leak does not always surface. Warm spots, unexplained water use and damp edges of flooring are the usual signs. Located properly before anything gets cut.'),
   ('drain', 'Roots in estate drainage', 'Landscaping planted with the estate has had thirty years to reach the drainage. Jetted out, with a camera afterwards to check the line.'),
   ('tap', 'Original tapware and cisterns', 'All installed within a few years of each other, all failing within a few years of each other. Quick to replace and it shows on the water bill.'),
   ('reno', 'Bathrooms and kitchens', 'Original fit-outs coming out across the suburb. Full plumbing scope, rough-in to fit-off, working in with your builder.'),
   ('storm', 'Stormwater and gutters', 'Mature estate planting drops into gutters and packs the stormwater line until it backs up against the house.'),
 ],
 'nearby_eyebrow': 'Around Penrith',
 'nearby_intro': 'We are out this way most days. If your suburb is not listed here, search the full list or just call and ask.',
 'nearby': ['plumber-penrith', 'plumber-st-marys', 'plumber-mount-druitt', 'plumber-richmond', 'plumber-windsor', 'plumber-rooty-hill'],
 'faqs': [
   ('Do you charge a call out fee in Glenmore Park?', FEE),
   ('What is a slab leak and how would I know I had one?', 'A leak in the pipework running under or through the concrete slab. Because it cannot surface easily, the signs are indirect: a water bill that has climbed for no reason, a warm patch on the floor if it is the hot line, damp at the edge of flooring, or the sound of running water with everything turned off. It can be located without cutting the whole floor open, and it is worth doing that before anybody starts breaking concrete.'),
   ('Everything seems to be failing at once. Is that normal?', 'For an estate built all in one go, yes. The houses were finished within a few years of each other with the same fittings and the same systems, so they reach the end of their life together too. It feels like bad luck and it is really just arithmetic.'),
   ('Do you come out to Glenmore Park after hours?', AH),
   council_q('Glenmore Park', 'Penrith City Council'),
   ('Are you licensed and insured?', LIC),
 ],
},

{
 'slug': 'plumber-parramatta', 'name': 'Parramatta', 'pc': '2150',
 'title': 'Plumber Parramatta | 24/7 Emergency | Straight Away Plumbing',
 'og': 'Plumber Parramatta | 24/7 Emergency Plumbing',
 'desc': 'Licensed plumber servicing Parramatta 2150. Apartments, strata and commercial - shared stacks, leaks, hot water. 24/7, $0 call out fee. Call 0403 322 290.',
 'ld_desc': 'Licensed plumber servicing Parramatta NSW 2150, including apartments, strata and commercial buildings. Shared stacks and common drainage, leaks, hot water plant and 24/7 emergency callouts.',
 'hero': 'Licensed plumbing across Parramatta - apartments, strata, commercial and older homes, 24 hours a day, with no call out fee.',
 'h2': 'High-Rise, Strata and Old Terraces',
 'paras': [
   'Parramatta is two cities in one. There is a dense centre full of apartment towers and commercial buildings, and around it pockets of housing that were here long before any of it.',
   'In the towers almost everything is shared: stacks, risers, hot water plant, common drainage. Your leak is frequently somebody else\'s pipe, and working out whose it is has to come before working out how to fix it.',
   'In the older homes it is exactly the opposite. Everything is yours, and most of it is original.',
 ],
 'cards_intro': 'Towers, commercial buildings and century-old houses, within a few streets of each other.',
 'cards': [
   ('block', 'Shared stacks and risers', 'In a tower, the fixture showing the problem is often several floors from the cause. We find where it actually is, and whether it is lot property or common property, before anybody is billed for it.'),
   ('alert', 'Leaks between units', 'Water in an apartment travels fast and through other people\'s homes. Located and stopped quickly, with the documentation your strata manager will want.'),
   ('hot', 'Hot water, individual and central', 'Individual units in apartments and central plant serving whole buildings. Repairs, replacements and the diagnosis of which one is actually at fault.'),
   ('wrench', 'Commercial and retail premises', 'Offices, shops and cafes through the centre. Blockages, tapware, hot water and compliance, scheduled around trading.'),
   ('jet', 'Tree roots in the older pockets', 'Away from the towers the drainage is old and the trees are older. Roots get into the joints and catch everything. Jetted clear and inspected.'),
   ('pipe', 'Original pipework in older homes', 'Low pressure and discoloured water on anything never repiped. Replaced in sections or in full.'),
 ],
 'nearby_eyebrow': 'Around Parramatta',
 'nearby_intro': 'We are through this part of Sydney most days. If your suburb is not listed here, search the full list or just call and ask.',
 'nearby': ['plumber-westmead', 'plumber-wentworthville', 'plumber-baulkham-hills', 'plumber-castle-hill', 'plumber-blacktown', 'plumber-penrith'],
 'faqs': [
   ('Do you charge a call out fee in Parramatta?', FEE),
   ('I am in an apartment. Is a blocked drain my problem or the building\'s?', STRATA),
   ('Do you work with strata managers and building managers?', 'Yes, regularly. Tell us who is handling it and we will deal with them directly, and provide whatever they need to approve common property work. For anything urgent we will make the building safe first and sort the paperwork after.'),
   ('There is water coming through my ceiling from the unit above. What now?', 'Call straight away, whatever the hour - water spreading through a building gets expensive very quickly. We will find the source, which is frequently not where it is appearing, and tell you whether it is the other lot, the common property or your own. Do not wait on the neighbour to organise it.'),
   council_q('Parramatta', 'City of Parramatta'),
   ('Are you licensed and insured?', LIC),
 ],
},

{
 'slug': 'plumber-westmead', 'name': 'Westmead', 'pc': '2145',
 'title': 'Plumber Westmead | 24/7 Emergency | Straight Away Plumbing',
 'og': 'Plumber Westmead | 24/7 Emergency Plumbing',
 'desc': 'Licensed plumber servicing Westmead 2145. Units, rentals and older homes - blocked drains, leaks, hot water. 24/7, $0 call out fee. Call 0403 322 290.',
 'ld_desc': 'Licensed plumber servicing Westmead NSW 2145, including apartments, rental property and older homes. Shared stacks, blocked drains, leaks, hot water systems and 24/7 emergency callouts.',
 'hero': 'Licensed plumbing across Westmead - units, rentals and older homes, 24 hours a day, with no call out fee and free quotes.',
 'h2': 'Units, Older Homes and Plenty of Rentals',
 'paras': [
   'Westmead is a mix of apartment blocks, older houses and a large institutional precinct, and the plumbing splits along much the same lines.',
   'In the units it is shared stacks and common property. In the older houses it is original drainage and pipework that has been in the ground a very long time.',
   'There is also a lot of rental and investor-owned property here, which usually means the person with the problem is not the person paying for it. We are used to working with agents, and to being the one who explains the job to somebody who is not standing in the room.',
 ],
 'cards_intro': 'Apartments, rentals and old houses, often on the same street.',
 'cards': [
   ('block', 'Shared stacks and common drainage', 'A blockage in the stack surfaces at the lowest fixture on the line. We establish where it really is and whose responsibility it is before anybody commits to paying.'),
   ('card', 'Work for agents and landlords', 'Quoted clearly, reported in writing, and scheduled with the tenant directly so the agent is not relaying messages. Invoiced to whoever is actually paying.'),
   ('jet', 'Tree roots in the older streets', 'Old drainage with old trees over it. Roots find the joints and catch everything. Cleared with a jetter and checked with a camera.'),
   ('pipe', 'Original pipework', 'Poor pressure and discoloured water in houses that have never been repiped. Replaced in sections or in full.'),
   ('hot', 'Hot water systems', 'Repairs and replacements in houses and units, including the tight installs common in older apartment blocks.'),
   ('alert', '24/7 emergency callouts', 'Burst pipes, leaks between units and sewer overflows, any hour, with no call out fee.'),
 ],
 'nearby_eyebrow': 'Around Parramatta',
 'nearby_intro': 'We are through this part of Sydney most days. If your suburb is not listed here, search the full list or just call and ask.',
 'nearby': ['plumber-parramatta', 'plumber-wentworthville', 'plumber-blacktown', 'plumber-baulkham-hills', 'plumber-castle-hill', 'plumber-penrith'],
 'faqs': [
   ('Do you charge a call out fee in Westmead?', FEE),
   ('I am a tenant. Can I call you directly?', 'You can call us any time and we will tell you what the problem is. Who authorises and pays for the work is between you, your agent and the owner, and for anything beyond an emergency we will need that sorted before we start. If it is an emergency we will make it safe first.'),
   ('I manage a rental. Do you deal with tenants directly?', 'Yes. Give us the tenant\'s details and we will arrange access with them, then report back to you in writing with what we found and what it cost. It saves a round of messages in both directions.'),
   ('I am in an apartment. Is a blocked drain my problem or the building\'s?', STRATA),
   council_q('Westmead', 'City of Parramatta'),
   ('Are you licensed and insured?', LIC),
 ],
},

{
 'slug': 'plumber-wentworthville', 'name': 'Wentworthville', 'pc': '2145',
 'title': 'Plumber Wentworthville | 24/7 | Straight Away Plumbing',
 'og': 'Plumber Wentworthville | 24/7 Emergency Plumbing',
 'desc': 'Licensed plumber servicing Wentworthville 2145. Granny flats, duplexes, units and older homes. 24/7, $0 call out fee. Call 0403 322 290.',
 'ld_desc': 'Licensed plumber servicing Wentworthville NSW 2145. Secondary dwellings and duplexes, blocked drains, tree roots, hot water systems, gas fitting and 24/7 emergency callouts.',
 'hero': 'Licensed plumbing across Wentworthville - 24 hours a day, with no call out fee and free quotes. Call and we will tell you straight away when we can be there.',
 'h2': 'Older Streets, and a Lot of Building Behind Them',
 'paras': [
   'Wentworthville is largely older housing with a steady amount of newer development mixed through it - unit blocks near the station, and a great many duplexes and secondary dwellings behind existing houses.',
   'That second category is where a lot of our work is. Putting a granny flat or a duplex on an existing block means running new drainage, water and gas to a property whose original services were never designed to carry it.',
   'The older houses themselves bring what housing of that age brings: earthenware sewer, corroded water pipe, and hot water that has outlived its second warranty.',
 ],
 'cards_intro': 'Old houses, new dwellings behind them, and the services that have to stretch to cover both.',
 'cards': [
   ('house', 'Granny flats and secondary dwellings', 'New drainage, water and gas runs to a dwelling at the back of an existing block, connected properly and to code rather than teed off whatever was nearest.'),
   ('jet', 'Tree roots in old drainage', 'Earthenware lines with decades of growth over them. Roots get in at the joints and catch everything. Jetted clear, then inspected with a camera.'),
   ('pipe', 'Original water pipe under load', 'An older service feeding more fixtures than it was ever sized for. Low pressure is often the service rather than the tapware, and it is worth checking which before replacing anything.'),
   ('block', 'Units and shared drainage', 'In the newer blocks, a blockage in shared drainage surfaces well away from its cause. We find where it actually is, and whose it is.'),
   ('hot', 'Hot water systems', 'Repairs and replacements, including second systems for a new dwelling at the rear.'),
   ('gas', 'Gas fitting', 'Cooktops, heaters, hot water and BBQ points, run and leak tested to code, including new runs to a secondary dwelling.'),
 ],
 'nearby_eyebrow': 'Around Parramatta',
 'nearby_intro': 'We are through this part of Sydney most days. If your suburb is not listed here, search the full list or just call and ask.',
 'nearby': ['plumber-westmead', 'plumber-parramatta', 'plumber-blacktown', 'plumber-baulkham-hills', 'plumber-doonside', 'plumber-quakers-hill'],
 'faqs': [
   ('Do you charge a call out fee in Wentworthville?', FEE),
   ('We are putting a granny flat at the back. What does the plumbing involve?', 'New drainage to the sewer, a water service sized for the extra fixtures, and gas if you are running it. The part people underestimate is the existing service - the original one was sized for one dwelling, and simply teeing off it often means neither place has decent pressure. Worth getting looked at before the slab goes down, not after.'),
   ('The pressure dropped after we added a second bathroom. Why?', 'Usually the incoming service rather than anything in the new work. More fixtures drawing on a pipe sized for fewer will show up as poor pressure everywhere, particularly when two things run at once. It is fixable, and it is a different job from replacing tapware.'),
   ('Do you come out to Wentworthville after hours?', AH),
   council_q('Wentworthville', 'Cumberland City Council'),
   ('Are you licensed and insured?', LIC),
 ],
},

{
 'slug': 'plumber-windsor', 'name': 'Windsor', 'pc': '2756',
 'title': 'Plumber Windsor | 24/7 Emergency | Straight Away Plumbing',
 'og': 'Plumber Windsor | 24/7 Emergency Plumbing',
 'desc': 'Licensed plumber servicing Windsor 2756. Tanks, pumps, stormwater, old drainage and hot water. 24/7, $0 call out fee. Call 0403 322 290.',
 'ld_desc': 'Licensed plumber servicing Windsor NSW 2756 in the Hawkesbury. Rainwater tanks and pumps, stormwater and drainage, old pipework, hot water systems and 24/7 emergency callouts.',
 'hero': 'Licensed plumbing across Windsor and the Hawkesbury - town and rural properties, 24 hours a day, with no call out fee.',
 'h2': 'A Historic Town on a Flood Plain',
 'paras': [
   'Windsor is one of the oldest towns in the country, and the plumbing runs the full span: genuinely old buildings in the centre, postwar housing around them, and semi-rural properties beyond.',
   'The river is the other factor. Properties on the flood plain deal with things most of Sydney never thinks about - water arriving from outside rather than from a pipe, and drainage that has to cope with a great deal more than an average storm.',
   'Out of town, plenty of properties run on tanks and pumps with on-site waste rather than mains and sewer, which is a different job again.',
 ],
 'cards_intro': 'An old town, a flood plain and a lot of rural property, each with its own demands.',
 'cards': [
   ('filter', 'Tanks, pumps and filtration', 'Rainwater tanks, pressure pumps and filtration on properties that are not on mains. Serviced, repaired and replaced, including pumps that short cycle or have stopped priming.'),
   ('storm', 'Stormwater and surface drainage', 'Drainage that has to move serious volume. Blocked and broken stormwater lines, downpipe connections and water sitting where it should not.'),
   ('jet', 'Old drainage in the town', 'The oldest lines around here predate most of the standards now in place. Roots, cracks and collapses. Jetted clear and inspected with a camera.'),
   ('pipe', 'Aging pipework', 'Low pressure and discoloured water on anything that has never been replaced. Renewed in sections or in full.'),
   ('hot', 'Hot water systems', 'Repairs and replacements in town and on rural properties, including systems running off tank water.'),
   ('gas', 'Gas fitting', 'Cooktops, heaters, hot water and BBQ points, installed and leak tested to code - including bottled gas where there is no mains connection.'),
 ],
 'nearby_eyebrow': 'Around the Hawkesbury',
 'nearby_intro': 'We are out through the Hawkesbury regularly. If your suburb is not listed here, search the full list or just call and ask.',
 'nearby': ['plumber-richmond', 'plumber-riverstone', 'plumber-marsden-park', 'plumber-schofields', 'plumber-penrith', 'plumber-box-hill'],
 'faqs': [
   ('Do you charge a call out fee in Windsor?', FEE),
   ('My property is on tank water. Can you still help?', 'Yes. Tanks, pressure pumps, filtration and the pipework around them are normal work for us. If the pump is short cycling, the pressure has dropped or the water has changed taste or colour, that is usually the pump or the filtration rather than the tank itself.'),
   ('Is there anything worth doing before flood season?', 'Clearing stormwater lines, gutters and downpipes is the obvious one, because they are the things that have to work hardest and they are cheap to check. It is also worth knowing where your main water shut off is and that it actually turns - the middle of an emergency is a poor time to find out it is seized.'),
   ('Do you come out to Windsor after hours?', AH),
   council_q('Windsor', 'Hawkesbury City Council'),
   ('Are you licensed and insured?', LIC),
 ],
},

{
 'slug': 'plumber-richmond', 'name': 'Richmond', 'pc': '2753',
 'title': 'Plumber Richmond | 24/7 Emergency | Straight Away Plumbing',
 'og': 'Plumber Richmond | 24/7 Emergency Plumbing',
 'desc': 'Licensed plumber servicing Richmond 2753. Rural properties, tanks, pumps, old drainage, hot water. 24/7, $0 call out fee. Call 0403 322 290.',
 'ld_desc': 'Licensed plumber servicing Richmond NSW 2753 in the Hawkesbury. Rainwater tanks and pumps, rural pipework, CCTV drain inspections, hot water systems and 24/7 emergency callouts.',
 'hero': 'Licensed plumbing across Richmond and the Hawkesbury - town and rural properties, 24 hours a day, with no call out fee.',
 'h2': 'Old Buildings and Rural Properties',
 'paras': [
   'Richmond has a historic centre, established housing around it, and rural properties spreading out from there. The plumbing changes completely depending which of the three you are in.',
   'In the older buildings the materials are the issue - drainage and pipework that predates most of the standards now in place, and which nobody has surveyed in a very long time.',
   'On the rural blocks it is self-sufficiency: tanks, pressure pumps, filtration, long pipe runs between buildings, and waste systems that are not connected to anything.',
 ],
 'cards_intro': 'Town and country in the same postcode, needing quite different work.',
 'cards': [
   ('filter', 'Tanks, pumps and filtration', 'Rainwater tanks, pressure pumps and filtration. Pumps that will not prime, pressure that has dropped away, and water that has changed taste or colour.'),
   ('house', 'Long rural pipe runs', 'Water and gas running between house, sheds and outbuildings, often installed decades ago by whoever was available. Traced, repaired and brought up to standard.'),
   ('jet', 'Old drainage', 'The oldest lines here are older than most of the rules. Roots, cracks and collapses, cleared with a jetter and assessed properly afterwards.'),
   ('cctv', 'CCTV inspections', 'On an old or large property nobody knows where the drainage runs. A camera and a locator answer that without digging a series of holes to find out.'),
   ('hot', 'Hot water systems', 'Repairs and replacements, including systems running off tank water and units a long way from the main house.'),
   ('storm', 'Stormwater and yard drainage', 'Water pooling against buildings after rain, blocked lines and downpipes that are not connected to anything useful.'),
 ],
 'nearby_eyebrow': 'Around the Hawkesbury',
 'nearby_intro': 'We are out through the Hawkesbury regularly. If your suburb is not listed here, search the full list or just call and ask.',
 'nearby': ['plumber-windsor', 'plumber-riverstone', 'plumber-marsden-park', 'plumber-schofields', 'plumber-penrith', 'plumber-glenmore-park'],
 'faqs': [
   ('Do you charge a call out fee in Richmond?', FEE),
   ('My pressure pump keeps switching on and off. What causes that?', 'Short cycling, and it is usually either a failed pressure vessel, a leak somewhere on the line, or a pump that has lost its prime. It is worth sorting quickly - a pump cycling constantly wears itself out, and if the cause is a leak you are also losing tank water you paid to collect.'),
   ('We are not connected to the sewer. Do you work on on-site waste systems?', 'We work on the plumbing side of them - the lines running to the system, and blockages or failures in that pipework. Tell us what the system is when you call and we will tell you straight away whether the job is ours or whether you need the system\'s own service agent.'),
   ('Do you come out to Richmond after hours?', AH),
   council_q('Richmond', 'Hawkesbury City Council'),
   ('Are you licensed and insured?', LIC),
 ],
},

]
