# -*- coding: utf-8 -*-
"""The Hills and the Blacktown belt: established housing, and what age does to it."""
from sub_data_a import FEE, LIC, AH, council_q

SUBS = [

{
 'slug': 'plumber-riverstone', 'name': 'Riverstone', 'pc': '2765',
 'title': 'Plumber Riverstone | 24/7 Emergency | Straight Away Plumbing',
 'og': 'Plumber Riverstone | 24/7 Emergency Plumbing',
 'desc': 'Licensed plumber servicing Riverstone 2765. Tree roots, blocked drains, old pipework, hot water. 24/7, $0 call out fee. Call 0403 322 290.',
 'ld_desc': 'Licensed plumber servicing Riverstone NSW 2765. Tree root removal, blocked drains, CCTV inspections, old pipework, hot water systems and 24/7 emergency callouts, with no call out fee.',
 'hero': 'Licensed plumbing across Riverstone - old streets and new estates alike, 24 hours a day, with no call out fee and free quotes.',
 'h2': 'An Old Town With New Suburbs Around It',
 'paras': [
   'Riverstone has a proper old town centre and a ring of brand-new release land around it. The two could not be less alike to work on.',
   'In the old streets it is what you would expect of housing that has been there a very long time: earthenware sewer lines with mature trees over them, pipework in materials nobody installs any more, and hot water units that have quietly outlived their warranty twice.',
   'In the new estates it is the opposite problem. Everything is new, and the faults are the ones that come from being built quickly rather than from age.',
 ],
 'cards_intro': 'Two very different kinds of property, sometimes a street apart.',
 'cards': [
   ('jet', 'Tree roots in old sewer lines', 'The oldest drainage around here is earthenware with decades of tree growth over it. Roots get in at the joints and catch everything. A jetter clears it; a camera tells you whether the pipe is worth keeping.'),
   ('cctv', 'Finding out what is actually down there', 'On an old property nobody knows where the lines run or what they are made of. A CCTV inspection answers both, usually faster and cheaper than digging to find out.'),
   ('pipe', 'Old pipework and low pressure', 'Dropping pressure and discoloured water usually mean corroded galvanised steel. Common in the older streets, and replaceable in sections or in full.'),
   ('drain', 'New estate drains', 'On the new side, a drain that has never run properly almost always has construction debris in it rather than a fault. A camera confirms it and a jetter clears it for good.'),
   ('hot', 'Hot water at both ends of the scale', 'Ancient units in the old streets, first-generation estate systems in the new ones. Repaired where a repair holds, replaced where it does not.'),
   ('gas', 'Gas fitting', 'Cooktops, heaters, hot water and BBQ points. On older homes that often means bringing the run up to standard rather than just connecting the appliance.'),
 ],
 'nearby_eyebrow': 'Around the North West',
 'nearby_intro': 'We are through this corridor most days. If your suburb is not listed here, search the full list or just call and ask.',
 'nearby': ['plumber-schofields', 'plumber-marsden-park', 'plumber-the-ponds', 'plumber-tallawong', 'plumber-quakers-hill', 'plumber-windsor'],
 'faqs': [
   ('Do you charge a call out fee in Riverstone?', FEE),
   ('How do I know whether my drain needs clearing or replacing?', 'A camera down the line. Clearing a blockage in a sound pipe is a straightforward job. If the pipe itself has cracked or collapsed, clearing it only buys time and it will be back. The inspection is what tells you which situation you are in, and it is worth doing before you spend money either way.'),
   ('What is the discoloured water in my older house?', 'Usually galvanised steel water pipe corroding from the inside. It narrows the bore, which is why the pressure drops, and the water picks up colour on the way through. It can be replaced in sections or in full, and we will tell you which makes sense for your place.'),
   ('Do you come out to Riverstone after hours?', AH),
   council_q('Riverstone', 'Blacktown City Council'),
   ('Are you licensed and insured?', LIC),
 ],
},

{
 'slug': 'plumber-kellyville', 'name': 'Kellyville', 'pc': '2155',
 'title': 'Plumber Kellyville | 24/7 Emergency | Straight Away Plumbing',
 'og': 'Plumber Kellyville | 24/7 Emergency Plumbing',
 'desc': 'Licensed plumber servicing Kellyville 2155. Hot water, water pressure, blocked drains, tanks and pumps. 24/7, $0 call out fee. Call 0403 322 290.',
 'ld_desc': 'Licensed plumber servicing Kellyville NSW 2155. Hot water systems, water pressure problems, blocked drains and tree roots, tanks and pumps, and 24/7 emergency callouts, with no call out fee.',
 'hero': 'Licensed plumbing across Kellyville - 24 hours a day, with no call out fee and free quotes. Call and we will tell you straight away when we can be there.',
 'h2': 'Big Houses, Big Gardens, Long Pipe Runs',
 'paras': [
   'Kellyville is mostly larger homes on decent blocks, built through the 1990s and 2000s, with older acreage still scattered through it.',
   'Bigger houses mean longer pipe runs, more fixtures and more hot water demand, which is why the complaints here are more often about pressure and capacity than about outright failures. A house with three bathrooms shows up a restriction that a small house would hide.',
   'The gardens are the other half of it. Thirty years of established landscaping over a drainage line eventually does what it always does.',
 ],
 'cards_intro': 'Larger homes on larger blocks produce their own particular set of complaints.',
 'cards': [
   ('hot', 'Hot water that runs out', 'Two bathrooms running at once on a system sized for less. Sometimes it is the unit, sometimes it is the plumbing around it. We work out which before anybody buys anything.'),
   ('tap', 'Pressure problems across a big house', 'Long runs and a lot of fixtures show up any restriction in the system. Usually traceable to one thing rather than needing the whole house repiped.'),
   ('drain', 'Roots in the drainage', 'Thirty years of garden over the sewer line. Roots find the joints and catch everything that passes. Jetted out, with a camera afterwards to check the pipe.'),
   ('storm', 'Stormwater across a large block', 'Big roofs, long runs and a lot of water to move. When it backs up it finds the house. Cleared and repaired properly rather than patched.'),
   ('reno', 'Renovations and extensions', 'Houses of this age are being reworked across the suburb. Full plumbing scope, rough-in to fit-off, working in with your builder and the other trades.'),
   ('filter', 'Tanks, pumps and filtration', 'On the acreage properties, tanks and pressure pumps are still doing the work. Serviced, repaired and replaced.'),
 ],
 'nearby_eyebrow': 'Around The Hills',
 'nearby_intro': 'We are across The Hills Shire most days. If your suburb is not listed here, search the full list or just call and ask.',
 'nearby': ['plumber-kellyville-ridge', 'plumber-rouse-hill', 'plumber-castle-hill', 'plumber-baulkham-hills', 'plumber-box-hill', 'plumber-the-ponds'],
 'faqs': [
   ('Do you charge a call out fee in Kellyville?', FEE),
   ('The hot water runs out when two showers are going. Is the unit too small?', 'Sometimes, but not always - and replacing it is the expensive way to find out. It can also be the tempering valve, the way the system is plumbed, or a fault that is dumping heat. Worth having it looked at properly before you buy a bigger unit you may not need.'),
   ('Water pressure is poor at one end of the house. Why only there?', 'Almost always a restriction in that branch rather than a whole-house problem - a partially closed valve, a blocked aerator, a failing flexible hose, or a section of pipe that has narrowed. On a long run it takes a bit of tracing, but it is usually one thing, not everything.'),
   ('Do you come out to Kellyville after hours?', AH),
   council_q('Kellyville', 'The Hills Shire'),
   ('Are you licensed and insured?', LIC),
 ],
},

{
 'slug': 'plumber-baulkham-hills', 'name': 'Baulkham Hills', 'pc': '2153',
 'title': 'Plumber Baulkham Hills | 24/7 Emergency | Straight Away Plumbing',
 'og': 'Plumber Baulkham Hills | 24/7 Emergency Plumbing',
 'desc': 'Licensed plumber servicing Baulkham Hills 2153. Blocked drains, tree roots, hot water, burst pipes and gas fitting. 24/7, $0 call out fee. Call 0403 322 290.',
 'ld_desc': 'Licensed plumber servicing Baulkham Hills NSW 2153, in The Hills Shire. Blocked drains and tree root removal, hot water systems, burst and leaking pipes, gas fitting and 24/7 emergency callouts, with no call out fee.',
 'hero': 'Licensed plumbing across Baulkham Hills and The Hills Shire - 24 hours a day, with no call out fee and free quotes. Call and we will tell you straight away when we can be there.',
 'h2': 'A Plumber Who Knows Older Homes',
 'paras': [
   'We are out through The Hills most weeks, and we cover Baulkham Hills 24 hours a day - with no call out fee at any hour, and no surcharge for a weekend or a public holiday.',
   'Baulkham Hills is an established suburb, and that shapes the work. Much of it went up from the 1960s onward on generous blocks, with gardens that have had fifty years to mature. Those trees are the reason half our calls out here are drains. The rest is what you would expect of houses that age: original pipework reaching the end of its life, hot water units well past their warranty, and bathrooms from the eighties finally being pulled out.',
   'None of that is a surprise if you have seen it before. We have, which usually means we can tell you what is going on before we start pulling things apart.',
 ],
 'cards_intro': 'Older housing stock and big established gardens produce a fairly predictable set of jobs.',
 'cards': [
   ('drain', 'Tree roots in the sewer', 'The single most common job out here. Roots find the joints in old earthenware and clay lines, get inside, and catch everything that goes past. We cut them out with a jetter, then put a camera down to see whether the pipe itself is still sound.'),
   ('jet', 'Old galvanised pipework', 'Dropping pressure and rusty looking water usually mean galvanised steel corroding from the inside. Houses of this era that have never been repiped get there eventually. It can be done in sections or in full - we will tell you which is worth it.'),
   ('hot', 'Hot water systems at end of life', 'A storage unit gets ten to fifteen years if it is looked after. Plenty out here are past that. We repair where a repair will actually hold and replace where it will not, rather than charging you twice.'),
   ('storm', 'Blocked gutters and stormwater', 'Mature trees drop a lot into gutters, and what gets past ends up packing the stormwater line. When it backs up the water comes down the side of the house instead. Better cleared before a storm than during one.'),
   ('reno', 'Bathroom and kitchen renovations', 'A lot of original bathrooms around here are being redone, and behind the tiles there is often pipework that should go at the same time. We handle the full scope, rough-in to fit-off, working in with your builder.'),
   ('gas', 'Gas fitting', 'Cooktops, heaters, hot water and BBQ points, installed and leak tested to code. On older homes that often means bringing the run up to standard rather than just connecting the new appliance.'),
 ],
 'nearby_eyebrow': 'Around The Hills',
 'nearby_intro': 'We are across The Hills Shire and out through the North West most days. If your suburb is not listed here, search the full list or just call and ask.',
 'nearby': ['plumber-castle-hill', 'plumber-kellyville', 'plumber-rouse-hill', 'plumber-parramatta', 'plumber-blacktown', 'plumber-quakers-hill'],
 'faqs': [
   ('Do you charge a call out fee to come to Baulkham Hills?', FEE),
   ('Why do Baulkham Hills homes get so many blocked drains?', 'Mature trees and older sewer lines. A lot of Baulkham Hills was built from the 1960s onward on generous blocks, and the trees planted then now have root systems sitting right on top of earthenware and clay sewer pipes. Roots find the joints, get in, and catch everything that passes. Cutting them out clears it, but a <a href="/services#cctv">CCTV inspection</a> is what tells you whether the pipe itself needs relining.'),
   ('Do you come out to Baulkham Hills after hours?', AH),
   ('My water pressure has dropped and the water looks rusty. What is it?', 'Usually old galvanised steel pipework corroding from the inside. It is common in houses of this era that have never been repiped. The pressure drops as the bore narrows and the water picks up colour on the way through. It can be replaced section by section or in full, and we will tell you which makes sense for your place.'),
   council_q('Baulkham Hills', 'The Hills Shire'),
   ('Are you licensed and insured?', LIC),
 ],
},

{
 'slug': 'plumber-castle-hill', 'name': 'Castle Hill', 'pc': '2154',
 'title': 'Plumber Castle Hill | 24/7 Emergency | Straight Away Plumbing',
 'og': 'Plumber Castle Hill | 24/7 Emergency Plumbing',
 'desc': 'Licensed plumber servicing Castle Hill 2154. Tree roots, old pipework, hot water, strata and units. 24/7, $0 call out fee. Call 0403 322 290.',
 'ld_desc': 'Licensed plumber servicing Castle Hill NSW 2154, in The Hills Shire. Tree root removal, aging pipework, hot water systems, strata and shared stacks, and 24/7 emergency callouts, with no call out fee.',
 'hero': 'Licensed plumbing across Castle Hill - established homes and newer apartments, 24 hours a day, with no call out fee and free quotes.',
 'h2': 'Established Streets and New Apartments',
 'paras': [
   'Castle Hill has two distinct kinds of property. The established streets are older homes on generous blocks with gardens that have had decades to grow. Closer in, there is a growing amount of newer apartment and townhouse development.',
   'The older homes bring the classic set: roots in the sewer, aging pipework, hot water units well past their warranty, and original bathrooms finally being pulled out.',
   'The newer buildings bring strata questions instead - shared stacks, common property, and blockages that show up a long way from where they actually are.',
 ],
 'cards_intro': 'Two kinds of building in one suburb, and two separate sets of problems.',
 'cards': [
   ('jet', 'Tree roots in the sewer', 'Big established gardens sitting over old drainage. Roots get into the joints and catch everything that passes. Cleared with a jetter, then a camera to check the condition of the pipe.'),
   ('pipe', 'Aging pipework', 'Falling pressure and discoloured water in a house that has never been repiped is usually galvanised steel corroding from the inside. Replaceable in sections or in full.'),
   ('hot', 'End-of-life hot water', 'A storage unit gets ten to fifteen years. Plenty around here are past that. We repair what will hold and replace what will not.'),
   ('block', 'Strata and shared stacks', 'In the newer buildings, a blockage in the stack shows up in the lowest bathroom on the line. We find where it really is before anybody pays for it.'),
   ('reno', 'Bathroom renovations', 'Original bathrooms coming out, often with pipework behind the tiles that should go at the same time. Full scope, rough-in to fit-off.'),
   ('gas', 'Gas fitting', 'Cooktops, heaters, hot water and BBQ points, installed and leak tested to code, including bringing older runs up to standard.'),
 ],
 'nearby_eyebrow': 'Around The Hills',
 'nearby_intro': 'We are across The Hills Shire most days. If your suburb is not listed here, search the full list or just call and ask.',
 'nearby': ['plumber-baulkham-hills', 'plumber-kellyville', 'plumber-rouse-hill', 'plumber-box-hill', 'plumber-parramatta', 'plumber-quakers-hill'],
 'faqs': [
   ('Do you charge a call out fee in Castle Hill?', FEE),
   ('I am in an apartment. Is a blocked drain my problem or the building\'s?', 'It depends where the blockage actually is. Inside your own fixtures and branch lines it is normally yours. In the shared stack or common drainage it is normally the building\'s. We find out which before anybody commits to paying, and we can put that in writing for your strata manager.'),
   ('Can tree roots be removed permanently?', 'The roots can be cut out completely, but if the pipe is cracked they will find their way back in - the crack is the invitation. Clearing it buys you time; relining or replacing that section is what stops it recurring. A camera inspection tells you which one you are looking at.'),
   ('Do you come out to Castle Hill after hours?', AH),
   council_q('Castle Hill', 'The Hills Shire'),
   ('Are you licensed and insured?', LIC),
 ],
},

{
 'slug': 'plumber-quakers-hill', 'name': 'Quakers Hill', 'pc': '2763',
 'title': 'Plumber Quakers Hill | 24/7 Emergency | Straight Away Plumbing',
 'og': 'Plumber Quakers Hill | 24/7 Emergency Plumbing',
 'desc': 'Licensed plumber servicing Quakers Hill 2763. Blocked drains, hot water, leaking taps, renovations. 24/7, $0 call out fee. Call 0403 322 290.',
 'ld_desc': 'Licensed plumber servicing Quakers Hill NSW 2763. Blocked and slow drains, tree roots, hot water systems, leaking taps and toilets, and 24/7 emergency callouts, with no call out fee.',
 'hero': 'Licensed plumbing across Quakers Hill - 24 hours a day, with no call out fee and free quotes. Call and we will tell you straight away when we can be there.',
 'h2': 'Eighties and Nineties Houses, Thirty Years On',
 'paras': [
   'Most of Quakers Hill went up through the 1980s and 1990s, which puts the housing at the age where original pipework, drainage and hot water have all had a long run and are starting to show it.',
   'It is rarely dramatic. It is a tap that has dripped for two years, a toilet that runs, a shower that drains slowly, a hot water system that takes longer than it used to. Individually minor, collectively expensive.',
   'The other half of it is the gardens. Thirty years of tree growth over a drainage line eventually gets into it.',
 ],
 'cards_intro': 'Thirty-year-old housing, and the slow, unglamorous problems that come with it.',
 'cards': [
   ('drain', 'Slow and blocked drains', 'Thirty years of grease, grit and hair narrows a waste line until it stops. A jetter takes it back to full bore, which a plunger never will.'),
   ('jet', 'Roots in the sewer line', 'Mature trees over older drainage. Roots find the joints and catch everything. Cleared properly, with a camera afterwards to check the pipe.'),
   ('hot', 'Hot water slowing down', 'Taking longer to heat, or running out sooner than it used to, usually means sediment or a failing element rather than a dead unit. Worth checking before replacing.'),
   ('tap', 'Dripping taps and running toilets', 'The most ignored plumbing problem there is, and the one that shows up most clearly on a water bill. Quick to fix and worth doing.'),
   ('reno', 'Bathrooms being redone', 'Original bathrooms are well overdue across the suburb. We handle the full plumbing scope and work in with your builder.'),
   ('storm', 'Gutters and stormwater', 'Established trees drop into gutters, and what gets past packs the stormwater line. Cleared before a storm rather than during one.'),
 ],
 'nearby_eyebrow': 'Around the North West',
 'nearby_intro': 'We are through this corridor most days. If your suburb is not listed here, search the full list or just call and ask.',
 'nearby': ['plumber-schofields', 'plumber-the-ponds', 'plumber-blacktown', 'plumber-kellyville-ridge', 'plumber-doonside', 'plumber-riverstone'],
 'faqs': [
   ('Do you charge a call out fee in Quakers Hill?', FEE),
   ('My shower drains slowly but it is not blocked. Is that worth fixing?', 'Yes, and it is cheaper to deal with now. A slow drain is a partly blocked one, and it only goes one direction. Clearing it properly with a jetter restores the full bore, where a plunger or a supermarket drain cleaner just moves the problem along a bit.'),
   ('Is a dripping tap really worth calling someone about?', 'A steady drip is thousands of litres a year, and it is usually a washer or a cartridge rather than a new tap. It is one of the few jobs where the repair reliably costs less than leaving it alone.'),
   ('Do you come out to Quakers Hill after hours?', AH),
   council_q('Quakers Hill', 'Blacktown City Council'),
   ('Are you licensed and insured?', LIC),
 ],
},

{
 'slug': 'plumber-blacktown', 'name': 'Blacktown', 'pc': '2148',
 'title': 'Plumber Blacktown | 24/7 Emergency | Straight Away Plumbing',
 'og': 'Plumber Blacktown | 24/7 Emergency Plumbing',
 'desc': 'Licensed plumber servicing Blacktown 2148. Tree roots, old pipework, blocked drains, hot water, units. 24/7, $0 call out fee. Call 0403 322 290.',
 'ld_desc': 'Licensed plumber servicing Blacktown NSW 2148. Tree root removal, corroded pipework, blocked drains, hot water systems, units and shared drainage, and 24/7 emergency callouts, with no call out fee.',
 'hero': 'Licensed plumbing across Blacktown - houses and units, 24 hours a day, with no call out fee and free quotes.',
 'h2': 'Postwar Houses and a Growing Centre',
 'paras': [
   'Blacktown covers a wide span. Much of the housing is postwar, built through the 1950s to the 1970s, and around the centre there is an increasing amount of unit development.',
   'In houses that old the pipework is the story. Earthenware sewer lines with decades of tree growth over them, galvanised water pipe that has been corroding from the inside since the day it went in, and hot water systems on their third or fourth replacement.',
   'In the units it is shared drainage and common property, where the fault is often nowhere near the bathroom it is showing up in.',
 ],
 'cards_intro': 'Seventy years of housing in one suburb, plus a growing number of units.',
 'cards': [
   ('jet', 'Tree roots and old sewer lines', 'Earthenware drainage under seventy-year-old trees. Roots get in at the joints and catch everything. Jetted out, then a camera to see whether the pipe is still worth keeping.'),
   ('pipe', 'Galvanised pipe corroding', 'Low pressure and rusty water in a house that has never been repiped. The pipe narrows from the inside until barely anything gets through. Replaced in sections or in full.'),
   ('block', 'Units and shared drainage', 'A blockage in shared drainage surfaces at the lowest fixture on the line. We find where it actually is, and whether it is yours or the building\'s.'),
   ('hot', 'Hot water systems', 'Repairs and replacements, including the awkward installs in older houses where the unit is in a difficult spot.'),
   ('cctv', 'Finding what is actually there', 'On an old property nobody knows what the drainage is made of or where it runs. A camera answers both without digging to find out.'),
   ('alert', 'Emergency callouts', 'Burst pipes, gas leaks and sewer overflows, 24 hours a day. Old pipework tends to fail at inconvenient times.'),
 ],
 'nearby_eyebrow': 'Around Blacktown',
 'nearby_intro': 'We are through this part of Western Sydney most days. If your suburb is not listed here, search the full list or just call and ask.',
 'nearby': ['plumber-doonside', 'plumber-rooty-hill', 'plumber-quakers-hill', 'plumber-mount-druitt', 'plumber-kellyville-ridge', 'plumber-parramatta'],
 'faqs': [
   ('Do you charge a call out fee in Blacktown?', FEE),
   ('What is the rusty water and low pressure in my older house?', 'Galvanised steel water pipe corroding from the inside. It is standard in houses of this era that have never been repiped - the bore narrows, the pressure drops, and the water picks up colour on the way through. It can be replaced section by section or in full, and we will tell you honestly which is worth doing.'),
   ('I am in a unit. Who pays for a blocked drain?', 'It depends where the blockage is. Inside your own fixtures and branch lines it is normally yours. In shared drainage or the stack it is normally the building\'s. We establish which before anybody commits to paying for it, and we can put it in writing for your strata manager.'),
   ('Do you come out to Blacktown after hours?', AH),
   council_q('Blacktown', 'Blacktown City Council'),
   ('Are you licensed and insured?', LIC),
 ],
},

{
 'slug': 'plumber-doonside', 'name': 'Doonside', 'pc': '2767',
 'title': 'Plumber Doonside | 24/7 Emergency | Straight Away Plumbing',
 'og': 'Plumber Doonside | 24/7 Emergency Plumbing',
 'desc': 'Licensed plumber servicing Doonside 2767. Tree roots, CCTV drain inspections, old pipework, hot water. 24/7, $0 call out fee. Call 0403 322 290.',
 'ld_desc': 'Licensed plumber servicing Doonside NSW 2767. Tree root removal, CCTV drain inspections, corroded pipework, hot water systems, gas fitting and 24/7 emergency callouts, with no call out fee.',
 'hero': 'Licensed plumbing across Doonside - 24 hours a day, with no call out fee and free quotes. Call and we will tell you straight away when we can be there.',
 'h2': 'Sixties and Seventies Housing',
 'paras': [
   'Doonside is largely 1960s and 1970s housing, which means the original plumbing has had somewhere between fifty and sixty years to age.',
   'At that point the materials themselves are the problem, not the maintenance. Earthenware sewer lines crack and let roots in. Galvanised water pipe narrows until the pressure goes. Neither gets better on its own, and neither is a plunger job.',
   'It is worth knowing what you have got before something fails, which usually means a camera down the drain and an honest look at what the water pipe is actually made of.',
 ],
 'cards_intro': 'Housing of this age has a predictable set of failures, and most of them are worth finding early.',
 'cards': [
   ('jet', 'Roots in cracked sewer lines', 'Fifty-year-old earthenware under mature trees. Once a joint opens, roots are in and the line catches everything. Jetted clear, then inspected properly.'),
   ('cctv', 'Camera inspections', 'The fastest way to find out whether a drain needs clearing or replacing. Cheaper than digging to find out, and it shows where the problem actually is rather than where it surfaced.'),
   ('pipe', 'Corroded galvanised pipe', 'Low pressure and discoloured water. The pipe narrows from the inside until almost nothing gets through. Replaceable section by section or in full.'),
   ('hot', 'Old hot water systems', 'Units well past their life, often in awkward positions in houses of this era. Repaired where sensible, replaced where not.'),
   ('storm', 'Gutters and stormwater', 'Decades of tree growth drop into gutters and pack the stormwater line. When it backs up the water goes down the wall instead of to the street.'),
   ('gas', 'Gas fitting', 'Cooktops, heaters, hot water and BBQ points, installed and leak tested to code, including bringing an older run up to standard first.'),
 ],
 'nearby_eyebrow': 'Around Blacktown',
 'nearby_intro': 'We are through this part of Western Sydney most days. If your suburb is not listed here, search the full list or just call and ask.',
 'nearby': ['plumber-blacktown', 'plumber-rooty-hill', 'plumber-quakers-hill', 'plumber-mount-druitt', 'plumber-riverstone', 'plumber-st-marys'],
 'faqs': [
   ('Do you charge a call out fee in Doonside?', FEE),
   ('Is it worth getting the drains looked at before anything goes wrong?', 'On a house this age, often yes - particularly before you spend money on landscaping or a renovation over the top of them. A camera inspection tells you whether the line is sound, cracked or already full of roots, and finding out at that point is a great deal cheaper than finding out afterwards.'),
   ('My drain keeps blocking even after it has been cleared. Why?', 'Because clearing it treats the symptom. If roots keep coming back, there is a crack or an open joint letting them in, and they will keep returning until that section is relined or replaced. A camera shows you the break rather than leaving you to guess.'),
   ('Do you come out to Doonside after hours?', AH),
   council_q('Doonside', 'Blacktown City Council'),
   ('Are you licensed and insured?', LIC),
 ],
},

{
 'slug': 'plumber-rooty-hill', 'name': 'Rooty Hill', 'pc': '2766',
 'title': 'Plumber Rooty Hill | 24/7 Emergency | Straight Away Plumbing',
 'og': 'Plumber Rooty Hill | 24/7 Emergency Plumbing',
 'desc': 'Licensed plumber servicing Rooty Hill 2766. Blocked drains, leak location, hot water, yard drainage. 24/7, $0 call out fee. Call 0403 322 290.',
 'ld_desc': 'Licensed plumber servicing Rooty Hill NSW 2766. Blocked drains and tree roots, leak location, hot water replacement, stormwater and yard drainage, and 24/7 emergency callouts, with no call out fee.',
 'hero': 'Licensed plumbing across Rooty Hill - 24 hours a day, with no call out fee and free quotes. Call and we will tell you straight away when we can be there.',
 'h2': 'Older Homes on Bigger Blocks',
 'paras': [
   'Rooty Hill is mostly older housing, a good deal of it on blocks larger than anything being subdivided now. The extra land is pleasant to live with and occasionally awkward to plumb.',
   'Longer runs from the house to the street mean more drainage to go wrong, and more of it sitting under lawn and garden rather than under concrete where you can get at it.',
   'The houses themselves are the usual story for the era: old sewer lines, tired water pipe, and hot water units that have been replaced once already and are due again.',
 ],
 'cards_intro': 'Bigger blocks mean more pipe in the ground, and more of it out of sight.',
 'cards': [
   ('jet', 'Long drainage runs with roots in them', 'More pipe between the house and the street means more joints for roots to find. A jetter clears the line; a camera tells you where the trouble actually is.'),
   ('cctv', 'Locating the problem on a big block', 'When drainage runs under lawn and garden, guessing is expensive. A camera and a locator put a mark on the ground before anybody digs a hole.'),
   ('hot', 'Hot water replacement', 'Units on their second life and heading for the end of it. An honest read on whether a repair will hold or whether you are better off replacing it.'),
   ('pipe', 'Burst and leaking pipes', 'Old pipe fails, and on a large block it can run for a long time before anybody notices. We locate it, stop the water and repair it properly.'),
   ('storm', 'Stormwater and yard drainage', 'Water pooling in the yard or sitting against the house after rain. Usually a blocked or broken stormwater line rather than the ground itself.'),
   ('gas', 'Gas fitting', 'Cooktops, heaters, hot water and BBQ points, installed and leak tested to code.'),
 ],
 'nearby_eyebrow': 'Around Blacktown',
 'nearby_intro': 'We are through this part of Western Sydney most days. If your suburb is not listed here, search the full list or just call and ask.',
 'nearby': ['plumber-blacktown', 'plumber-doonside', 'plumber-mount-druitt', 'plumber-st-marys', 'plumber-quakers-hill', 'plumber-marsden-park'],
 'faqs': [
   ('Do you charge a call out fee in Rooty Hill?', FEE),
   ('My water bill has jumped but I cannot see a leak. What now?', 'On a large block that usually means an underground leak between the meter and the house, which can run for months without surfacing. It can be located without digging up the yard, and finding it properly is a lot cheaper than the water you are losing.'),
   ('Water pools in the yard after rain. Is that a plumbing problem?', 'Often, yes. If it is close to the house or it shows up in the same place every time, it is usually a blocked or broken stormwater line rather than the ground. Worth looking at, because water sitting against a house does not stay outside it forever.'),
   ('Do you come out to Rooty Hill after hours?', AH),
   council_q('Rooty Hill', 'Blacktown City Council'),
   ('Are you licensed and insured?', LIC),
 ],
},

]
